### ISSUE TITLE
Feature Request: Save to Picture Gallery

### ISSUE THREAD

**Issue by jtrees** [vector-im/riotX-android#973] opened 2020-02-07 10:19 UTC
Please add the ability to save a received picture to the Android gallery.

When receiving images in an encrypted room there is currently no way (that I know of) to get that image (decrypted) into the Android gallery. This severely limits the usefulness of Riot as a mobile instant messenger for me.

**Comment by bmarty** [comment] 2020-02-25 18:24
Duplicate of #677

**Comment by jtrees** [comment] 2020-02-25 22:35
These issues sound like different things. Also note how this issue has six thumbs-up and the other one has none.

**Comment by bmarty** [comment] 2020-02-26 07:30
Yes, my bad, it's actually related to #677

**Comment by bmarty** [comment] 2020-02-27 08:12
So we can:
- add a share menu item on the media viewer, using the same share icon.
- add an entry "Save..." to the message bottom sheet for all events with attachment (image/file/etc.)

 It should work for both clear and e2e image.

**Closed** 2020-04-20 10:24 UTC
Labels: feature:media
