### ISSUE TITLE
m.image height and widget are float, not int

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riotX-android#363] opened 2019-07-15 08:58 UTC
[The spec mentions](https://matrix.org/docs/spec/client_server/unstable#m-image) an `m.image`s content.info.{h,w} must be integers, however when sending a message today my bridge broke complaining that they were floats: https://github.com/tulir/mautrix-whatsapp/issues/80

They should be converted to floats to remain spec compliant.

**Comment by bmarty** [comment] 2019-07-16 10:01
Hello @anoadragon453 ,

Are you sure the image was sent from RiotX? I've checked in the model, and we only use `Int` for all the data in ImageInfo (and since the beginning): https://github.com/vector-im/riotX-android/blob/develop/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/message/ImageInfo.kt

Benoit

**Comment by anoadragon453** [comment] 2019-07-16 10:02
Hm, it was sent from Riot X but it could be something on the bridge side? Odd though, since the bridge is written in Golang which is typed as well. I'll try the mautrix-whatsapp side again.

**Comment by tulir** [comment] 2019-07-16 10:24
RiotX definitely sends all integers as floats, you can check the event json in the synapse db.

Maybe the problem is the JSON serializer? The Moshi repo had a bunch of int/float mixup issues, although none of them seemed to be about serialization.

**Comment by ganfra** [comment] 2019-07-17 06:38
I've just checked the json sent to the server, and all integers are well sent as integers.
```
{
   "msgtype": "m.image", 
   "body": "00000PORTRAIT_00000_BURST20190716211350956.jpg",
   "info": {
     "mimetype": "image\/jpeg",
     "w": 4032,
     "h": 3024,
    "size": 3839019,
     "rotation": 0,
    "orientation": 0
   },
}
```

And the data from the sync is identical.

**Comment by bmarty** [comment] 2019-07-17 06:44
@anoadragon453 any information about the device where riotx was installed? Model, os version, etc. A user agent would be ideal.
Thanks

**Comment by tulir** [comment] 2019-07-17 06:55
My Huawei P20 Pro (Android 9.0) at least does it reliably for every image. Just sent one to [#riotx:matrix.org](https://matrix.to/#/!tTIucwUZLRtKnXeurb:matrix.org/$15633462288241wmjUJ:maunium.net?via=matrix.org&via=privacytools.io&via=feneas.org).

"View Source" on Riot Web and RiotX converted them back to ints before showing, but old Riot Android view source and the server db definitely show floats

**Comment by anoadragon453** [comment] 2019-07-17 23:43
Pixel XL, Android 9.0

**Comment by bmarty** [comment] 2019-07-18 08:26
I think there is something strange in RiotX. 

The view source shows:

When sending an image from RiotX:
- on RiotX: Int
- on Riot Android: **Float**
- on Riot Web: Int
- on Riot iOS: Int

When sending an image from Riot Android:
- on RiotX: Int
- on Riot Android: Int
- on Riot Web: Int
- on Riot iOS: Int

**Comment by bmarty** [comment] 2019-09-24 20:31
Hi @anoadragon453 can we close this issue?

**Comment by tulir** [comment] 2019-09-24 21:11
The issue still seems to be there on build 936

**Comment by MTRNord** [comment] 2020-06-29 14:29
This issue happened now too. See the above ruma issue. It seems like if you fetch the data via the `/_matrix/client/r0/rooms/:room_id/event/:event_id` endpoint it returns floats. But in riot-web they show up as integers. (Maybe in the sync synapse does make them ints?)

**Comment by tulir** [comment] 2020-06-29 14:31
> (Maybe in the sync synapse does make them ints?)

No, it's riot web (as I said above: https://github.com/vector-im/riotX-android/issues/363#issuecomment-512128543)

**Comment by MTRNord** [comment] 2020-06-29 15:24
@tulir whoops ok. Yeah but this still happens anyway

**Comment by auscompgeek** [comment] 2020-07-17 11:22
Note that this means ~~RiotX~~ Element Android cannot send images to v6 rooms.

**Comment by ganfra** [comment] 2020-07-20 15:22
Json is actually doesn't really know between double or integer, it's just "numbers"
The client is responsible for typing then. In RiotX this issue is caused by loosing the information of the content when sending through Workers. It will be fixed in next release, thanks for pointing it :)

**Comment by diller444** [comment] 2020-07-28 08:38
Huawei P Smart Z, Android 10.0

**Comment by bmarty** [comment] 2020-08-03 12:59
Should be fixed by #1766

**Closed by bmarty** 2020-08-03 12:59 UTC

**Comment by tulir** [comment] 2020-08-03 13:15
It doesn't work on latest develop (G-b3379)

**Comment by diller444** [comment] 2020-08-14 18:54
still the same
