### ISSUE TITLE
sharing files other than images crashes riotx

### ISSUE THREAD

**Issue by lub** [vector-im/riotX-android#987] opened 2020-02-11 15:57 UTC
Doesn't matter if e2ee or plain. I've sent a rageshake.

steps to reproduce:

1. go to another app (e.g.my music player)
2. share a file
3. select riotx
4. select room
5. (app crashed)

**Comment by bmarty** [comment] 2020-02-12 11:29
Thanks for reporting the issue and for the rageshake. We will investigate

**Comment by returntrip** [comment] 2020-02-12 12:41
Does NOT happen for me on `0.15.0 [40015002] (G-b1855)`

**Comment by lub** [comment] 2020-02-12 12:51
hmm, maybe this is particularly a problem with music files? (e.g. mp3, m4a, ..)

**Comment by returntrip** [comment] 2020-02-12 12:56
Just tried with a .m4a and that worked. Not sure why does not work for you. Maybe check the app permissions?

**Comment by bmarty** [comment] 2020-02-13 22:27
A missing permission issue has been fixed in #1010 . This is maybe the root cause of the pb.
But the crash should also occurs for images.

**Comment by bmarty** [comment] 2020-02-13 22:29
Here are the log from the rageshake:
```
Thread: main, Exception: java.lang.IllegalStateException: firstFrame must not be null
at im.vector.matrix.android.internal.session.room.send.LocalEchoEventFactory.createVideoEvent(LocalEchoEventFactory.kt:238)
at im.vector.matrix.android.internal.session.room.send.LocalEchoEventFactory.createMediaEvent(LocalEchoEventFactory.kt:178)
at im.vector.matrix.android.internal.session.room.send.DefaultSendService.sendMedia(DefaultSendService.kt:192)
```

I will see how to handle that gracefully

**Comment by bmarty** [comment] 2020-02-26 14:39
Ok, fixed by 4ba8a42977cd7e48623d48f6b4d6b4e8bdabafb0. It should not crash anymore

The route cause is not fixed though. RiotX should not handled audio file has video file.

**Closed** 2020-03-03 09:05 UTC

**Comment by bmarty** [comment] 2020-03-04 09:59
Thanks for having closed the issue :)
