### ISSUE TITLE
Element doesn't follow or have an option to follow system theme

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riotX-android#1710] opened 2020-07-17 11:46 UTC
I just installed Element 1.0.0 on Android 10 Go Edition / Nokia 1 TA-1047 and while my system theme is marked as dark, Element started with light theme and the theme settings don't have an option to follow system theme.

**Comment by bmarty** [comment] 2020-07-17 11:57
Duplicate of #904

**Closed by bmarty** 2020-07-17 11:57 UTC
