### ISSUE TITLE
Lost unsent messages during upgrade

### ISSUE THREAD

**Issue by tg-x** [vector-im/riotX-android#1346] opened 2020-05-10 09:52 UTC
1. type some messages that dont get sent right away due to network issues
2. upgrade app to 0.19.0
3. app shows importing accounts screen
4. unsent messages are lost

**Comment by bmarty** [comment] 2020-05-25 22:23
Yes, this is a duplicate of #669

**Closed by bmarty** 2020-05-25 22:23 UTC
