### ISSUE TITLE
Show presence of DM conversation partner in DM list

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/riotX-android#1834] opened 2020-07-28 15:57 UTC
This puzzled me for a while, the web riot/element client shows conversation partners in the DM list as online/offline and such, but it does not show up on the Android app so far, have plans been made to make that so?

**Comment by BillCarsonFr** [comment] 2020-07-30 13:57
Duplicate of #70

**Closed by BillCarsonFr** 2020-07-30 13:57 UTC
