### ISSUE TITLE
Unable To save Photos

### ISSUE THREAD

**Issue by Flam3z** [vector-im/riotX-android#704] opened 2019-11-23 04:27 UTC
When viewing a sent photo by any user, there is no option to save the photo when you are in the chat and when you view it in a bigger scale when pressing to view.

**Comment by bmarty** [comment] 2019-11-29 14:03
Yes, this will be handled soon, thanks for creating the issue

**Comment by Soundtoxin** [comment] 2020-01-12 05:51
This has been bothering me as well. I am trying to use RiotX full-time and this is probably the biggest usability issue right now. Looking forward to a fix.

**Comment by duncanturk** [comment] 2020-05-05 18:17
Is this covered by #973 ?

**Comment by auscompgeek** [comment] 2020-05-06 09:24
It does look like #973 is a duplicate of this issue.

**Comment by duncanturk** [comment] 2020-06-19 10:05
This may be closed than @Flam3z

**Closed** 2020-07-19 05:05 UTC
