### ISSUE TITLE
view images in room by swipe

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#1236] opened 2020-04-16 00:59 UTC
Feature request.

Now:
1. open room with many images in room
1. tap on image for see it on full screen mode
1. If user want see next image in room (for example many photos of tourist hike) - He need press "return", scroll to next image, press next photo and again and again...

Need: 
1. open room with many images in room
1. tap on image for see it on full screen mode
1. Swipe to left - show next image in room in full screen mode, swipe to right - show previous image in room in full screen mode.

**Comment by arthurlutz** [comment] 2020-05-19 15:48
Thanks @progserega for reporting this... 

This is the missing feature that's currently preventing me from encouraging family members to switch from the riot-android they are using to riot-x

**Comment by bmarty** [comment] 2020-05-25 22:32
Duplicate of #327

**Closed by bmarty** 2020-05-25 22:32 UTC
