### ISSUE TITLE
Font size setting is not applied on next run of the application

### ISSUE THREAD

**Issue by Ai-rin** [vector-im/riotX-android#805] opened 2020-01-05 20:51 UTC
If I set non-default font size, the setting itself is preserved on next run, but actual font size isn't.
I'm on XIaomi Redmi Note 4X with standard MIUI global (11.0.2 currently)

**Comment by maralorn** [comment] 2020-02-06 08:11
I can reproduce this issue, but this is a duplicate of #645

**Comment by bmarty** [comment] 2020-05-14 00:21
Yes, duplicate.

**Closed by bmarty** 2020-05-14 00:21 UTC
Labels: type:usersettings
