### ISSUE TITLE
well-known lookup doesn't work yet in the login flow

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#946] opened 2020-02-03 14:36 UTC
Typing "hacklab.fi" doesn't fill in "https://matrix.hacklab.fi", instead it just says https://hacklab.fi isn't a valid Matrix server

**Comment by cyphar** [comment] 2020-02-07 20:32
I also hit this, and it's a pretty big a step down in terms of ease-of-use when you look at it as "the first thing you see as a new user". As far as I can tell, the `SRV` lookup also isn't working (I have both setup for my server). The few folks who are using my homeserver have no idea what the correct matrix server name is (they just know their account is called `@foo:cyphar.com`).

So having the aliasing system for homeservers would help, but I really think there should also be some kind of "log in with an account" option within to allow you to just type in `@foo:cyphar.com`. That's what users see all the time within Matrix (it's how you reference other users, and how you log in with every other client), so I don't get why it's been replaced with a login flow which (while prettier) requires going through three screens.

**Comment by aaronraimist** [comment] 2020-02-15 22:11
Duplicate of #778

**Closed** 2020-02-25 18:27 UTC
Labels: feature:wellknown, screen:login
