### ISSUE TITLE
Quoting 'in reply to' is shown in sender's language, not recipient's

### ISSUE THREAD

**Issue by d2dyno** [vector-im/riotX-android#429] opened 2019-07-24 17:50 UTC
For example, a French user replying to me will show 'in reply to USERNAME' in French, not English.

![Screenshot_20190725-015305](https://user-images.githubusercontent.com/2421939/61852580-6760fd80-ae7f-11e9-904f-8e17a51b38b5.jpg)

**Comment by BillCarsonFr** [comment] 2019-08-18 21:35
Thanks, riotX need to implement rich replies instead of relying on fallback text
Duplicate of #174

**Closed by BillCarsonFr** 2019-08-18 21:35 UTC
