### ISSUE TITLE
Logging in with the wrong server?

### ISSUE THREAD

**Issue by Munfred** [vector-im/riotX-android#663] opened 2019-11-04 08:34 UTC
I have an account on the `matrix.org` server with user `munfred`, and an account on `matrix.munfred.com` with user `munfred`. They both have the same password. I noticed that when trying to log into RiotX and specifying that it should use `matrix.munfred.com` as the homeserver, it actually logs me into `matrix.org` with the user `@munfred:matrix.org`.

**Comment by bmarty** [comment] 2019-11-04 13:45
That's annoying... and due to the refacto done to handle SSO login.
To fix the issue you should type the homeserver url, then enter the login and password.
The issue will be naturally fixed by the implementation of #613 , which is started

**Comment by saveriob** [comment] 2019-11-15 10:05
I can confirm that everything works as expected if you first type the homeserver url and then the user/password pair.

**Comment by bmarty** [comment] 2019-12-03 13:09
Fixed by #689

**Closed by bmarty** 2019-12-03 13:09 UTC
