### ISSUE TITLE
It's easy to accidentally cancel an in progress verification, and you can't recover

### ISSUE THREAD

**Issue by ara4n** [vector-im/riotX-android#1167] opened 2020-03-24 23:47 UTC
Amandine tried to verify me; I got a popup and started the process; i then accidentally hit a room in the list in the background, which took me into that room, cancelling or at least hiding the verification UI.  I have no way to get back into it, and now when Amandine tries to verify me again, i get no popup.

**Comment by BillCarsonFr** [comment] 2020-03-26 09:03
Duplicate of #1096

-> New design implemented in  https://github.com/vector-im/riotX-android/pull/1162 will prevent accidental dissmissal

As per current design for this phase, in order to resume you have to go back to the DM room with A and tap back the verification tile to resume

**Closed by BillCarsonFr** 2020-03-26 09:03 UTC
