### ISSUE TITLE
Clicking on not yet downloaded image in timeline leads to unresponsive app screen

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riotX-android#1586] opened 2020-07-01 07:08 UTC
I use overloaded matrix server and images are downloaded too slow. And clicking on not yet downloaded image in RiotX timeline (when it shows yet as transparent rectangle) leads to unresponsive app screen, seems because RiotX shows this transparent rectangle at full screen, that intercept all clicks. Clicking "back" button help to solve this problem, but will be better to prevent this "feature" :)

**Comment by bmarty** [comment] 2020-07-01 07:15
Duplicate of #885

**Closed by bmarty** 2020-07-01 07:15 UTC
