### ISSUE TITLE
Reactions does only work with emojis

### ISSUE THREAD

**Issue by lugino-emeritus** [vector-im/riotX-android#483] opened 2019-08-13 18:06 UTC
In RiotX only emoji reactions are visible. It would be great to also view random unicode strings (upto *n* bytes) in a reaction. Then it would be also possible to do simple surveys:
![grafik](https://user-images.githubusercontent.com/26658839/62965617-bd351f80-be05-11e9-8633-0e3a152791c3.png)

edit:
RiotX does not work with a single letter as reaction key as `A`. But probably #307 will solve this issue.

**Comment by BillCarsonFr** [comment] 2019-08-18 21:07
Duplicate of #307

**Closed by BillCarsonFr** 2019-08-18 21:07 UTC
