### ISSUE TITLE
Add multi account support

### ISSUE THREAD

**Issue by mister-monster** [vector-im/riotX-android#750] opened 2019-12-07 02:11 UTC
Some users manage multiple accounts, often on multiple servers. Currently it is difficult to manage this, especially on mobile. On desktop people can just use the web client for each server they have an account on, it is more difficult if they have accounts on the same server.

Proper multiaccount support would require all accounts to be signed in simultaneously to ensure notifications and avoid encryption problems.

**Comment by bmarty** [comment] 2019-12-09 13:19
Duplicate of #26

**Closed by bmarty** 2019-12-09 13:19 UTC

**Comment by mister-monster** [comment] 2019-12-10 08:33
Alright, I looked for an open or closed issue on this topic but I didn't find it, I suppose I didn't look hard enough.

**Comment by jittygitty** [comment] 2022-05-16 22:30
Seems that "for now", the only way is: https://github.com/matrix-org/sygnal/issues/70
But not sure exactly how one is supposed to go about implementing the proposed workaround/solution.
