### ISSUE TITLE
Make room colored, instead of bold, when unread.

### ISSUE THREAD

**Issue by jtagcat** [vector-im/riotX-android#440] opened 2019-07-26 13:49 UTC
Instead of making the room name bold, when unread, change color. This allows better overview and allows use of bold elsewhere. I think the 3rd (gradient) one looks the best (though the gradient should be more white/intense/use a secondary color).
![oo](https://user-images.githubusercontent.com/38327267/61955970-ae4c1180-afab-11e9-8923-10e139a408dc.png)

**Comment by violoncelloCH** [comment] 2019-07-27 11:55
how about adding a bubble (in riot green ?) with the number of unread messages?
this way you easily see which rooms have unread messages (visual/color feedback) and can also see how many unread messages there are...

**Comment by jtagcat** [comment] 2019-07-27 12:48
Adding a bubble might be okay, but numbering messages is not useful at all - It doesn't give you much information and it has been found to stress everyone up a notch. The feature issue of somebody is writing indicator would be much more useful in understaning the room before opening it.

A bubble would also need it's own location, taking up space. You can't make it around the profile pic fully, as it's already reserved. Elsewhere it would be too small or too geeky/bad ui.

And.. additionally it makes the user want to click the bubble, not the message's location, making it harder to press, if it's at a spesific location.

Pardon for turning your idea down.

**Comment by cjdelisle** [comment] 2019-08-05 12:44
On my phone (Nexus x5) there is no indication that the room has unread messages at all, apparently the bold font doesn't work correctly.

**Comment by BillCarsonFr** [comment] 2019-08-29 09:42
I think we can close this in favor of
Duplicate of #524

**Closed by BillCarsonFr** 2019-08-29 09:42 UTC

**Comment by jtagcat** [comment] 2019-08-29 18:41
@BillCarsonFr Combo of both would be great, thoughts?
