### ISSUE TITLE
Cropping pictures causes rendering problems

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#1394] opened 2020-05-23 13:12 UTC
I cropped a (vertical) screenshot in current RiotX. Seems like the result still contains the height information of the original image (in the EXIF data?), and the Riots render by EXIF(?) information instead of checking the real data? When I enlarge the image, both Riots however render fine.

Can you maybe clone the issue to Riot-Web?

• Here is how the preview looks on RiotX:
  ![IMG_20200523_150911](https://user-images.githubusercontent.com/10520767/82731504-b2e67100-9d07-11ea-8e97-fb99b94c799e.jpg)

• Here is how the preview looks on Riot-Web:
  ![Bildschirmfoto von 2020-05-23 15-06-43](https://user-images.githubusercontent.com/10520767/82731513-c7c30480-9d07-11ea-9592-5e40a8650235.png)

**Comment by T-bond** [comment] 2020-05-23 21:29
Duplicate of #1381

**Closed** 2020-05-23 21:31 UTC
