### ISSUE TITLE
Zoom into image, not just align it to width

### ISSUE THREAD

**Issue by a000a** [vector-im/riotX-android#1627] opened 2020-07-05 14:39 UTC
The possibilty to zoom into an image would be great.
At the moment it is just aligned to screen width as far as I see

**Comment by duncanturk** [comment] 2020-07-05 15:05
May be a duplicate of #1123

**Comment by a000a** [comment] 2020-07-05 15:10
> May be a duplicate of #1123

Yep sorry. Tested it in un-encrypted. There zooming works.

**Closed** 2020-07-07 07:47 UTC
